# .pre-commit-config.yaml
# See https://pre-commit.com/ for usage and config

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [--maxkb=500]
  - repo: local
    hooks:
      - id: dprint
        name: dprint
        entry: dprint fmt --incremental=true --allow-no-files
        language: node
        pass_filenames: false
        additional_dependencies: ["dprint"]
      - id: ruff_format
        name: Ruff format
        stages: [commit]
        language: system
        entry: pixi run ruff format
        types: [python]
      - id: ruff_lint
        name: Ruff lint
        stages: [commit]
        language: system
        entry: pixi run ruff check --fix
        types: [python]
      - id: pydocstringformatter
        name: pydocstringformatter
        stages: [commit]
        language: system
        entry: pixi run pydocstringformatter
        types: [python]
      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pixi run mypy
        types: [python]
        require_serial: true
      - id: pydoclint
        name: pydoclint
        stages: [commit]
        language: system
        entry: pixi run pydoclint
        types: [python]
        require_serial: true
# Exclude files that are generated
# exclude: |
#   (?x)(
#     ^environment.yml|
#     ^pixi.lock|
#   )
